FROM lantuzi/wan480:1.6
# COPY wan2.1_i2v_720p_14B_fp8_e4m3fn.safetensors ./comfyui/models/diffusion_models/wan2.1_i2v_720p_14B_fp8_e4m3fn.safetensors
# COPY wan2.1_i2v_480p_14B_bf16.safetensors ./comfyui/models/diffusion_models/wan2.1_i2v_480p_14B_bf16.safetensors
# COPY clip_vision_h.safetensors ./comfyui/models/clip_vision/
# COPY 4xLSDIR.pth ./comfyui/models/upscale_models/
# COPY film_net_fp32.pt ./comfyui/models/vfi/
COPY handler.py ./